---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: qbittorrent
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: qbittorrent
            version: 23.6.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false

    postRenderers:
        - kustomize:
            patches:
              - target:
                  version: v1
                  kind: Deployment
                  name: qbittorrent
                patch: |
                  - op: add
                    path: /spec/template/spec/containers/1/resources/limits/squat.ai~1tun
                    value: 1
    values:
        TZ: America/Montreal
        addons:
            gluetun:
                enabled: true
                container:
                    env:
                        OPENVPN_PASSWORD: ${VPN_PASSWORD}
                        OPENVPN_USER: ${VPN_USER}
                        SERVER_REGIONS: ${VPN_SERVER_REGIONS}
                        VPN_PORT_FORWARDING: ${VPN_PORT_FORWARDING}
                        VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
                        DNS_KEEP_NAMESERVER: "on"
                        DOT: "off"
                        FIREWALL: "on"
                        FIREWALL_INPUT_PORTS: "10095"
                        FIREWALL_OUTBOUND_SUBNETS: "${VPN_EXCLUDED_NETWORK}"
        credentials:
            s3:
                type: s3
                url: "${S3URL}"
                bucket: "${S3BUCKET}"
                accessKey: "${S3ID}"
                secretKey: "${S3KEY}"
                encrKey: "${S3ENCRKEY}"
        ingress:
            main:
                enabled: true
                ingressClassName: external
                hosts:
                    - host: qbit.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
        persistence:
            media:
                enabled: true
                existingClaim: media-nfs-pvc
                targetSelector:
                    main:
                        main:
                            mountPath: /data
            downloads:
                enabled: true
                existingClaim: downloads-nfs-pvc
                targetSelector:
                    main:
                        main:
                            mountPath: /downloads
            config:
                enabled: true
                mountPath: /config
                volsync:
                    - credentials: s3
                      dest:
                        enabled: true
                      name: s3
                      src:
                        enabled: true
                      type: restic
        qbitportforward:
            QBT_PASSWORD: ${QBT_PASSWORD}
            QBT_USERNAME: ${QBT_USERNAME}
            enabled: true
