---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: qbittorrent
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: qbittorrent
            version: 20.0.11
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: qbittorrent
    values:
        TZ: America/Montreal
        addons:
            vpn:
                env:
                    OPENVPN_PASSWORD:
                        name: OPENVPN_PASSWORD
                        value: ${VPN_PASSWORD}
                    OPENVPN_USER:
                        name: OPENVPN_USER
                        value: ${VPN_USER}
                    SERVER_REGIONS:
                        name: SERVER_REGIONS
                        value: ${VPN_SERVER_REGIONS}
                    VPN_PORT_FORWARDING:
                        name: VPN_PORT_FORWARDING
                        value: ${VPN_PORT_FORWARDING}
                    VPN_SERVICE_PROVIDER:
                        name: VPN_SERVICE_PROVIDER
                        value: ${VPN_SERVICE_PROVIDER}
                excludedNetworks_IPv4:
                    - ${VPN_EXCLUDED_NETWORK}
                killSwitch: true
                type: gluetun
        credentials:
            s3:
                type: s3
                url: "${S3URL}"
                bucket: "${S3BUCKET}"
                accessKey: "${S3ID}"
                secretKey: "${S3KEY}"
                encrKey: "${S3ENCRKEY}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: qbit.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            media:
                enabled: true
                existingClaim: media-nfs-pvc
                targetSelector:
                    main:
                        main:
                            mountPath: /data
            downloads:
                enabled: true
                existingClaim: downloads-nfs-pvc
                targetSelector:
                    main:
                        main:
                            mountPath: /downloads
            config:
                enabled: true
                mountPath: /config
                volsync:
                    - credentials: s3
                      dest:
                        enabled: true
                      name: s3
                      src:
                        enabled: true
                      type: restic
        qbitportforward:
            QBT_PASSWORD: ${QBT_PASSWORD}
            QBT_USERNAME: ${QBIT_USERNAME}
            enabled: true
