apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia/ks.yaml
  - cloudflared/ks.yaml
  - generic-device-plugin.yaml
  - grafana/ks.yaml
  - home-assistant/ks.yaml
  - ipmi-tools/ks.yaml
  - lldap/ks.yaml
  - mealie/ks.yaml
  - media
  - scrypted/ks.yaml
  - teslamate/ks.yaml
  - nvidia-device-plugin/ks.yaml
  - nvidia-device-plugin/runtime-class.yaml

