---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: radarr
            version: 23.20.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: radarr
    values:
        TZ: America/Montreal
        credentials:
            s3:
                type: s3
                url: "${S3URL}"
                bucket: "${S3BUCKET}"
                accessKey: "${S3ID}"
                secretKey: "${S3KEY}"
                encrKey: "${S3ENCRKEY}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: radarr.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            media:
                enabled: true
                existingClaim: media-movies-nfs-pvc
                targetSelector:
                    main:
                        main:
                            mountPath: /data
            downloads:
                enabled: true
                existingClaim: downloads-nfs-pvc
                targetSelector:
                    main:
                        main:
                            mountPath: /downloads
            config:
                enabled: true
                targetSelector:
                    exportarr:
                        exportarr:
                            mountPath: /config
                            readOnly: true
                    main:
                        main:
                            mountPath: /config
                volsync:
                    - credentials: s3
                      dest:
                        enabled: true
                      name: s3
                      src:
                        enabled: true
                      type: restic
