apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:m2EeKCawHGEFH3yi555ANjkM8PfsTsjSDg1TgBQnbSoFsmvpbEyUSKD3Rgd3isxAoblVZsxVC0kempaZb6WX0h4=,iv:2VD2e6yG01FQZPDE78pQxjODaLZb5xgTQzDsgQBrU8g=,tag:Kb2frXmynO6ESinRdBJf/w==,type:comment]
    #ENC[AES256_GCM,data:YR8zfqncKXlOXqGyosBxqKxReA7i5c/MRElCxHIDPycm7lzgcwLpaZjTgZg=,iv:GXkgJVVj3DhVtHMBUgIn79w2LZ1tTuvCAyCZ90u5pus=,tag:e5rfBzOImgt2a1orszURiQ==,type:comment]
    VIP: ENC[AES256_GCM,data:Dpy7UIXofIj6paNX,iv:AveE1/ZRgMX8cFHM4C5uErmmTv79ErbfPD+n7jdb/R0=,tag:meqzx+8f8UzTTUQO9WdSVg==,type:str]
    #ENC[AES256_GCM,data:KeeOk4jkNNSA3P1BiXNVCYawK4SqOB8Xfb8=,iv:oIs/iqYbuh3lxvjVfhQaWQeo/z0xs+dMChIBTPzpM0c=,tag:PEI6g3xLs+LCIV150LEJug==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:KDq452xIEOyMEeknWwNc,iv:AaOIHE1XrRh49KG9/MolE36XfkpDTNJX9hbD8pK2/Vw=,tag:uRrM2oXwlzeLDpel/5abAw==,type:str]
    #ENC[AES256_GCM,data:0PaUApSyorT/JxYWKa53KfN0YeHHgtRT86Mc/3z2bAngsQ==,iv:NPlFLRMlxJ7HJwLr6ZORiRA2YgvcmlWbaUR9YYG8WGk=,tag:9xMNY7wpr5VRySuCyxU7CA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Bx//BGf7KBoWIA==,iv:1w9jsenIKmEB3YiHhDR5V+CgP/eYz4gEOnl7sjWHYn4=,tag:8g4CQXgVS7Qd4FwbAw2xHA==,type:str]
    #ENC[AES256_GCM,data:8CZfslrDuEszkP7geklIyJQ0Rktb2i6j8L5RAFON55iD5Dqd8OpPKPBNwcfIg7Q=,iv:g5K9BmXti41gDJ8njNudD1DmG7paRuDIZsdXr2V12vE=,tag:W5CtXHXSamBfuQ/2ZyJ00w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:QaZXo3sE0oInSmABP4T/lFxuq1WNZL+/eQ==,iv:xouLdgW325foj2fE3QI2qiOMoZV8c7nH9Bvj8d1SaoA=,tag:SB8pnFDQrljisI7siL/IcA==,type:str]
    #ENC[AES256_GCM,data:uDri4g60zMxeIEHQOMfQxq/v3ePJ+ItASD3O98Fd8TOpQTF0PyUCBXLWNXm0dxDm+/68KOTGqPsBYTT4aqF7nyObPaDzScJMhWjSiO1Jm0A=,iv:DyhM02BwnJnVI30aDaP6TjZ5tJd7GEcJBb4aHH4+VK0=,tag:2wzniG3JXhWRkzul/8DTVw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:jbWZfnTOOVqZ84+/,iv:iSrxAlRaf2CMB8DRl6zMVNq8rDuGueQh58BssQKC3+w=,tag:pz67nrqn3NGUPfSTOIHCGg==,type:str]
    #ENC[AES256_GCM,data:uGQnPDeDjbTEaEUkqA8o7ZoCyKFxfgnj0R5NiuK4pSsUHMuvL8S2ADxaOMwDBRa5Cz3aEhTJVxY=,iv:+R8EjIQ2AfCDqMzZfNt6Z7mhcyBf+8xiYXtKmNlDkc4=,tag:i/DOCuGj/wUN7iLXBWeS0g==,type:comment]
    #ENC[AES256_GCM,data:wUWPPdIlmxSp6pRSWYWEPil0+dnaxQ5rSQ==,iv:d7yoHUNwwWg+YJtEwcJqpPhM2R9HVDEbFBqapAkHeQc=,tag:9vF3Zn7dbOJB1Ecac3AVMg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Gtu8SX7bEDjnnnQzrQKjztMQ1SuW2/2iC05uj0xwB2ktAAxTE+kUjOE=,iv:eNkua5uSylA/PFoQg3YWmOPaJQfAnDLfTmhwm5Ne9iE=,tag:ETSQDkIR8h3/V2Sw42u5uQ==,type:str]
    #ENC[AES256_GCM,data:fWJzTbJQ0UyswC4fLw==,iv:wCUQvQa+Gel5xQkMmf6if5eC7ob6wIBzngPHqjGJZe4=,tag:TAIh7Ht6F8JSimjrHWTxQw==,type:comment]
    PODNET: ENC[AES256_GCM,data:GnvQG7UxDi1/6iGjig==,iv:rRrcXwbA87E3GQdIrWyzFCZoRX8XhRXYKO8Wux+rqXI=,tag:E63DGkqBjs2mo+H3kQpB4A==,type:str]
    SVCNET: ENC[AES256_GCM,data:n8j25XbCXK7hRHEW7A==,iv:h6l8zi4HoeaPE6/vk7OCNb+ytecyqyBesicopG1RMFA=,tag:e0ai0zZmJGniSXBYd9MLow==,type:str]
    #ENC[AES256_GCM,data:3Bb299wKQhqOQ1wf,iv:KB1ZP2W4lE6nmXzQH2xWyP3GZK3PzUotBtCqiqKbhtM=,tag:gGGdLys8Au4xUoXTxrZiWw==,type:comment]
    S3URL: ENC[AES256_GCM,data:J0bjgacIvTDy5gRB/tfmtbDlvtsxxzwdqtuMEDLQg6j71pqo35Y=,iv:ATwVuK7snJbQRGnoEK+SsuByGzNBMSlHst0nMmNvQC0=,tag:b1XAAu7cD+DiLNhD8WeaYA==,type:str]
    S3BUCKET: ENC[AES256_GCM,data:y6au3om42Ju1wdG1GprAdA6inw==,iv:MbNatg5EClAvhwjCanDZXsx5xG3d+boOKOn7tkskLxA=,tag:4ITkbDyYmRc45Ey8t7p/Bg==,type:str]
    S3ID: ENC[AES256_GCM,data:ecRg01ypgrxmMftg3uBpHAvexzMqjfAoJw==,iv:n2GCJTpDZzzCdvdx+XEM9tIcNbgq+g9XmQVT4iHz4n4=,tag:3lEVG5O/jrsM/wSXG3ixyQ==,type:str]
    S3KEY: ENC[AES256_GCM,data:2dRf8LDJeAr+Z2Oj/mYvLODWJ+C1wg7FeiTcgkJZdw==,iv:vDr234rVoBbPAEJ7eOQCD1d4Nh/tJaNU1gNhW/XwBpc=,tag:lYpeKjXvH1nUAb8fj/zPzQ==,type:str]
    S3ENCRKEY: ENC[AES256_GCM,data:+79+AJexI4gE8U0c5mMi4/wd,iv:DJNHHovnZ6g7tJ3PjcgwwZvo5fgx+8kL88oR47XbCCs=,tag:fGmRChVvSdk8Gbl00TPlww==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Pjl3NEkarbMsKNrrvA==,iv:muvB2YK6AIctWgJstn/2A5KrEVYD7Z9B4NEsPMMTio8=,tag:RdZakdYuqUVC8kvleSsYSg==,type:str]
    MAIN_EMAIL: ENC[AES256_GCM,data:CQgKaoEQrh/kPsOICp28FXxn,iv:FCj0suPe+NZZGiiRc7si+jh0RA2/YQQUBxwljl7/Khk=,tag:CHQ3lJD/tvI5aKTscLZNKA==,type:str]
    TRUENAS_PORT: ENC[AES256_GCM,data:25na,iv:drrn1smSAIIjFx6KmMltqI5+VpJpFGMMtKVb5psuPbo=,tag:0HPwrqZ39lPNDS7sC7HZJQ==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:Y2vpD1MivDSjF7I=,iv:IzsXlh0JUucpUdr2i2dBR6D8RFpN4/LJ8OFWfimEJBg=,tag:8KNH/K8gqbIVD/gzrVS+Eg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:jcTE7Q1FHnpSQjgv,iv:NdL0WzCDgGNFHJXFTE/1cZzLiG90CmLrcqyu2irXLIg=,tag:1YS7zfHwgq5RelQdg+Gixg==,type:str]
    PLEX_PORT: ENC[AES256_GCM,data:U/XkZlI=,iv:p8s3lC1rPjUs6GRh6sPeYcecPKzlUSMeEsYEC9RlAgk=,tag:9Exlazaeqv4byP+2atHFDw==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:2MeDpdpPJIklkk0H4MOk94UVINI=,iv:ZVqI8GBou5HVhKVn9boDh+PopweyR/cpsKRpdSh0sLk=,tag:uVU7aaPKZWyJNEz5VlXyLw==,type:str]
    QBIT_USERNAME: ENC[AES256_GCM,data:grBn9is=,iv:O7XGSa+Wh+W7bLP1MNk3KwAaB9HQOBB7sxITieoRuWk=,tag:V2/y10f/K9lVkXtuJD4H7g==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:MFk6dNtH+hS4yw==,iv:mQvFh1cHWNbjYcSlrPXtipwrOhTAl9O0iUhERyrJc5I=,tag:Tx6ZPli+AcQSnNsG8ydWBA==,type:str]
    CLOUDFLARE_API_KEY: ""
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:eutSMhI4C88FkECRw6anaJeR0HX7/KyIl3Xz+XgeN34Ut114Gwm2TA==,iv:Quaz9ioJH0fr0yz2px5oE0MPrEUlij8nqmB7CVJJYdI=,tag:JBcuJZZl9Ix/W9Dux2LxRg==,type:str]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:Xy6e2qHhVJMTeuZdVNqs6Nxv2KOZWXKy54QJmTXvj0IZt44xEGiBXU8oGZpaiqr6zi3lIxWRn3r+9au3eduI1DMbw5Qr7j/twUrYh0x6M7xEDxzwsJ9ROZOxx4lMBsvHxL1WPvJ13r+7JBjC/rpmxTThdZhJ9LDwNYFSqx9VRbmMBcgl1qpIR23Id0IFLhX02tC6zn7cAPQCkRttcZNh4LPGLaaNce2f+MGaaj8LKwsaWczfjPlY9g==,iv:enpxhQN0V3HXUoG2yZxXXY1wHChjAqMn9356Rrmeozg=,tag:OQcyIVBm/AI2zkSSCiT0Ng==,type:str]
    VPN_PASSWORD: ENC[AES256_GCM,data:9k3+Ol3iYVJJyQ==,iv:Am3Cfrl+TeRoHrxm65Kfx+X5pUyJY3DXvQo26EPkEEs=,tag:tpKrCZv/XhalFPmzGnbmEQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:wtIRtTjj6kA=,iv:BEcaNiAedkTNUZOJSfRiDyAqQ8Ek87uV0mTkKawCT70=,tag:B5+qCNZAl4FtpMhkAdYidw==,type:str]
    VPN_SERVER_REGIONS: ENC[AES256_GCM,data:DQ1Z2RqDA4A/Dnc=,iv:fm0Wz12CQMEBm/BuXkOzsBm8nA/3u8IzCku3gcx7pII=,tag:JBNUHS3qXlbz4KuKwP8ZXg==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:DjY=,iv:vP77cTyS3C96MivtPQgkd4AI7Y+B1S4CDZMDnSrQhwM=,tag:QYJ47brFrKv15KgWHCuofQ==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:LrtCMVqRTwRccTQDsHHkRfVIy1WqzE8=,iv:QQZ8gDfWzSUvM7OKb3T+O6+//wpFeYzvmx+oRk/eSZ4=,tag:c4OzsJK7AK7WThgPq0QACQ==,type:str]
    VPN_EXCLUDED_NETWORK: ENC[AES256_GCM,data:spKr9P/KTpehu/c+/A==,iv:aMZOLyqm2et1RJprU1VZprfeY7bxje463gzdl51LoVY=,tag:xBTiouq1vDu1Pvf2fjqOqw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:XDjn8Q==,iv:jjkkppJBYDLCFOQpY8Sn08RJKKHfMCmf5HmyVrbWldw=,tag:xIlQj3yJzfUy9FnaoVFkuw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArajVEUHFhbzBjRUluRmdv
            eU5XWWtDam5iQnR1eFNhVUFmdFpRRkY4bEJzCjc3Vk53Sy8vSjBmTUMvYU1ERm1S
            STk1WmJEZ2R4YklweVZEeCtOR28vTHcKLS0tIFFUenU2aTdvV2F3aG9JWjBKUUZ5
            MWIvT25oMWxiOFdwSDBDNkVSWFh0NWMKjqgHGNkrzaLkX+IlHTZiXoUtbekAZLe0
            X0qJoYsVNMjNC5tyWPl3DD7AcqOIqDvsyCz9yugdlmn35HW8xiL2pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T15:57:34Z"
    mac: ENC[AES256_GCM,data:5GSbpDZXSDRlHRln/jqTHTsUFgQzf2wWmI5FAbdBLXVqsEAihFWEvRkizZx/Ip6CqWvvfLEpg5H1i9HWPvZGjOPdbJkxhc1VPzZK0ePFkAvsvQTPEvn9LtkYXwqs+kM2/jwT5EJ+yZHwhIkvnVNClzuSIoHnDLaBCpTePYn3efE=,iv:rOOITP6WBqaPmxNHI9ePa/nGB+YkjzYqxEfrRhYtzlw=,tag:y+VjKCgm4efvv3HZYvHX6g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
