apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3jUmd2BCkqWipg2H2Z0v+ghxXonMueEfTsWqiYbcYwmyqoaLU3qMqnnqXegnFpNwpdHA3qpkdcdLK32rTiXjbOH9d/4IIWD5Nl0Nvhw089m29IQ3JEOwKRrtrITNTSTK2FRcnEl1lpjs1RrCfeqVF5/EMoFCAIiXWolEicGM4QCDDt82aEa3roXjRX4R4LYHKhuW7Dd1D4KzZXnFrrRdVrbg3Q5ZgvW++TraIyuc6TgxNOd68XF1VW7JrbnL8V/kOJq7vDGDromME8GGI/5ITkLII3rDgFQTG+EItHGry1dyLlq5PKk88lZgqIbFfz+FzTnSUWWdV2fy7rbz7oUb44yA9ZuzdWQqZJ4YT8i3nPSYXtC2O5rzbsR2oAC6VxIC,iv:NdBomJMAqClRSpjBMjsDDX+GXEVG21uUBybFORs1ASI=,tag:I6s8kEaF6bAve1rn0hPoKg==,type:str]
    identity.pub: ENC[AES256_GCM,data:C2DyWliI6gxASagyTZttirb28B4QC0BsUCAfg5eGzRUuz0PxWe8Cm/KHcsplDoGVH9Uxh3AhocO7GIHqChRg1NsyWlL9DIV89ivbM+zKXuf4OihFEhbeWK7Sd9f6PXkO95C7w4Mqys7wAmf8ez/oeQFQYpGXhzGXVy9MejXrvysfuqPoWlXIi2HOnD4hIl66cyHDHRdDByx+57p6tUMiPXKk4JzxbqIdDml3rPeDdk0kG4Pv/D9+81u7MI8AEuI52fJ5quCIichpDv41dQ==,iv:zc2QeyD6Q8/HZelQVJM6Hp3WbFFJON14ZzzhkTrDC+A=,tag:aq+ACaLRlB/llc2TcCUL7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:Hucb87l1o7PXMdnGhIc4cO+8mb9fqjkzempSj7UzMN7mH3AxedxJVtaVU6qK58/7quPuTTD1StK1o721zFw8xRTsDY6aMAhs4FIrMfz/0FfgDJYMeQ064mUSr+GQF+jiU8O3O/yFvpCJJ3B5FS+AGkH5ZePKjrwdIEHcq56VUUhDSN3+nxSYSHchJPe5NmG+7JqtCtGfJK5LgS8nGokTNaJ6ZnMHeouCrH94,iv:gZ64+M2u8E3XDOw9bI9vSq3K6n7/7flA90JwNOg0zdU=,tag:wEOTdOQ+LRcIg9vVDrOQxw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN3ZBaTJtN09ZeHpnZmFT
            U1lMZUw1L0ZNTVlvcStXbjJXYnhXRzhTTFZ3CmJudVhSTGVWYWZsNDE2OGlNWmd0
            ZWMzbzc4K2Q1K2dIOHZkNGNkYzVsS1UKLS0tIHNPNndNS2NvUFlRSDJ4NFdCS3VF
            aXhDcmcrbS8wd1pWalgyaThMRm1INGcKVxAuT1fIJRB5XJnIN19Nk4eOJ//NFmHx
            M5XWb6lrZBB+IX/ixYpNzFU1vmisNth2UMGNrXoHPSM6hHcXwAGHUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-01T04:21:18Z"
    mac: ENC[AES256_GCM,data:RON1TLf0Zz8wFpqxEFDM9iL4qr4YiclWAGfrjKhAIBObljnSZ9iZWTQQvoa8pQwnXEIAdbk1AdlJK1/kdDLVdb9djGyaWjCFxhX8K8csaB5gNK4C3ejs60hXCU4kYudWSu97z+7+TmPVFLMsJD5LrwmN1t1482BROWty8kNeRMI=,iv:OXVy5dpeUBgzbPm6IWCL9YHlYI+qtRcnwztN8vAWKp0=,tag:xukq5OtkZR1Ho9GqWegJxw==,type:str]
    shamir_threshold: 3
    version: 3.13.0
