apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+f4FnLP1b58ErmY1CHXihGc8aJSihuorDN8T9UI4E2+a6iJe336iYsCgjLAX6uX8puB6ZFjQQEou5e52sjhMEjvcZE4YlMVOi1q2xjBCPYDN9uSwqF78yAJ+Eik/jn1ypb56tisyA9utzPScIXw8yvr3iyOaV30PUUVSzKfBfTRpbBonlOD38Rt6cl2uKHo+an6vwqKP+zOhDCuK4SbSEQQ8nrrjggFyJpr7LPIWdqyq17DhKVs4p3w0Wd5yosCKWEniavjkI/07TPUfHGomEUur/7X/3j18a/Dmr1LCLBvkR+v+eFiNwlglhkOWZJtzaTcFFUeET3n8iTfheqDuc5hEALom55PIer2h/g1HcDgMk4tN+Y9cQmph9rMKe/ky,iv:BQ4VGyP0OSHH5fDjIfydSbesZVMUyXmn6wwsI0QGb80=,tag:H7AH5qelUDzjD9xB1kOzfA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NxxVBmZKG/sLqzfInIzmXRmMLxRrf+BQJwmIfViTepbB7iCokCGet/4wqvVCTByD3j0QFfECNUcGiZATVXyVUyUy2pzeeygc4QagFaN4zjqhv5K6GKbvZSk1TwP8nD0nwb1eVci5mSS6yyUU8+dLuODz/xdQi7NMayxkYKEJfTEHQ1uODukdm72ziOb48FlDRg0rLdm+x7aHYqLDbgLgpGE0DeXSfLRNkgyTbvW4nY6E3aBAte/P+mckf1GqgxRfzCAQoIRD44A0xf3BOQ==,iv:/4BVaDHh7imfB3goVHYL9WI+C8Q5eHBw2iY1cLokf2I=,tag:62BAwCK5Ioxb+LU6juUlCw==,type:str]
    known_hosts: ENC[AES256_GCM,data:TXX1BOksyya5UGWmuHF/duRxHrrXsgXQJoPPgxM1bDKC9v17DYlM1IwKAtAso7V0BnmMxnfoRQonRQTolL/unAYiVWYbm/BkqpahFXpQsoQh+xzIbmCq1h3See9XlY3nbAddfgSa88It4uaOWcDcJqCrKJz+AR68+W3kWXglIGmnsU1ZeDX/Doe4YUGHy9r79jq6M7VUaYmhnqdluQVJ303RmKyW/xOHFNaF,iv:uKz+PjWLxIsYWsfufqIzp7v6D1uOVDq4521vIcQ6sfg=,tag:b582mr/+mxavhz4UXkoZkA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdmp5MFkvRnFIaDNDbXlY
            RmNhdGxpcGdvWENFRlZwMkZ1WFMrUktTelVJCi9DT090c1M1Z1BZSUwxTmhBbVRm
            RHdIbDJ5Q2VOc3BlWUdrVFBmUzVmUHMKLS0tIGZNcnpwTWpOSW5mbFdFNldlbkhF
            TWtRY0FNcUsyemEwTkpqR3R2d1UxQlEK9RriBMVuefMs8AE9hKImFjnrDFFylFOn
            y2kw7p7QLxBxKJmf0LPu/4LspYalyCoMVr6VCroA2vjFFKAuNU4hNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-01T09:15:04Z"
    mac: ENC[AES256_GCM,data:pyXi5x51UXl+RopUTW1DEjst9WfJncIFCis7v9nbHHpKDlcAH9GxkjpVFc5psG+VND2yKeTVZ7nxqQKuQx75DGdtuUnf8oSh7wbDKhWEAIQ657Wb74jagw6Pj2GLQ3gbvc53qiVxUf+Dad70XyJ+oT6uta6Q0qMplDbm5dV6aKo=,iv:pNTjGtogwRpFUH9yT7uyLORu//rbBTLP854syHHQMRk=,tag:cHgQwT3j3/N361u7092EeA==,type:str]
    shamir_threshold: 3
    version: 3.13.0
