apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B3NdRqv+NTCoIAoAKsVVlfeb+Dz6YRQAMCJVPs+Xmbiqjm3Gs4gQYC6qnboiMI/MpknUXPmmo0FmeJo/7sVdMjd3klcm4cqtdnMPyiZSPhO1KlUftkUH75t6YBwu2GDa5oBU4I+fza6IkDNu/l1+wEgi3AtIHOSPxScJiHPtCsOl7mMYhI9gjHWXjccFHvU/8+wgwEWhbK1lvI5MFwiOxjm7Bn67175FK4Sg7QRUvfQCL7mLIl6bAqNQO8CyoArTiBp2Rl6SEZwTOdMYhByWAs91OA4yE9OKfTb+nF0+fRbkehwD6y56YlNcY49kGSS5X4EenSelK3Jo8CHKIXGkHTaRcXBqJP5jASrHCDtVD0bZDRtq10521mK9lvZbyZ9i,iv:5MqEfy4RgJHISjCYayCIH9hMlVaKrMqQqhZTQzhJK0c=,tag:usnDNE1RZuUEUznTwsUcmw==,type:str]
    identity.pub: ENC[AES256_GCM,data:oDoVL9LnXqMeew91QCO/Z+Xf4EEXOChNDwZbgUJciK0s+ECzdGu/ekl7Am3kI7gs2GflkJEM7qOtshI6JkvbKDPvFitQYMdPJ1pn5kwKjQz37jjf0pR2Dfx3mtBuerQoAC6rbbjS3iUsF1ff59fsROqQBg4jCrXMca1KAyo0DL+3O441TFxoRBg5F78jTsTgNd51hdFZuoXDRgtPJL7OiI5FNPxYdNvY2BXCdkGzo2IE96j6vho7/E2nt7rNoJeXZtKwNRUMvolyC4vsiw==,iv:DdYpgd7nwAVx813Bvb3lFDLcsmYfFq7DX48Ynx18oGE=,tag:tjZBeG7hVO5F2xR9oJCGJw==,type:str]
    known_hosts: ENC[AES256_GCM,data:/wjb/LV8X+CwargZDJFBl8NrgEN8phSdlBNW2wsIA+StsXq4aytJWtXckK4PsQGVzrItsuPFcELKHqcxdCmNbbvqezlaB/eWI1PzA/VWz04cX9VImA6VP2ZzTMLv3aPBpTv1eS0wqxJPdvQ5XS3apmkcE48F4ik5Atc0fURFuLZ9mNbse1menAYFrRdkHBR07FGmv+UstEdSVkjpaTGeZYB9/mRinxNJevRr,iv:CVZE3bh10kKoJ0GCLVyiTD9zJ8aBzjcQpfPTsKve9As=,tag:GkIWQNFMkpL0b1VLHDfX/g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcVgzeXovU2U0aWtoa0hB
            VE1DekZuak9rUStKc1VUbFFkQkg3NmozQndVCmtGVTN1d09JYk10QzQzY2ROcEVw
            SXlhK0R1VE41WE9wTi96UnQwN0lNWWcKLS0tIGFsb2dPbHZvanNET3ZTK0JHVmg2
            WTl4SW1xbXhmUkdlYmVDNzJNdnBXOWsK7rkvQ7C8D+V3Q1EkXA2z+hccratepV4h
            Neha2EVcYfsO02ybp/kaPaYWxyhiUi5657IrCWvCHXZ8XEH7QYcUpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-01T04:49:44Z"
    mac: ENC[AES256_GCM,data:ue4cZ+zLtQ1rnPZmS90i49IPm5grwknQ61gvhpduRT3f4lT7s4SBkLpIZ9HViL/4fb5WtuAXgpgE7l0Ai2A/SIuqE1oPbdQ9v9Zd+gI8S2tZ8YhhIyJQbzDYW9lL8vdphYw+oicjTyqdbfbI2u9udi/pLdABUlyL6cku4PO5JGk=,iv:9NBNtN+zOJDOM1IedsNUuZ2KTe2Hs/QBciEYRajK7U4=,tag:3zk8LJBcdQR5P82WL8vzyg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
