---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-service
    namespace: external-service
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: external-service
    values:
        ingress:
            main:
                annotations:
                    traefik.frontend.passHostHeader: "false"
                enabled: true
                hosts:
                    - host: truenas.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        service:
            main:
                enabled: true
                externalIP: ${TRUENAS_IP}
                ports:
                    main:
                        enabled: true
                        port: ${TRUENAS_PORT}
                        protocol: https
                type: ExternalIP
                useSlice: false
