---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: lead-ai
    namespace: lead-ai
spec:
    interval: 15m
    chart:
        spec:
            chart: custom-app
            version: 13.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: lead-ai
    values:
        TZ: America/Montreal
        ingress:
            main:
                enabled: true
                hosts:
                    - host: leadai.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        service:
            main:
                enabled: true
                ports:
                    main:
                        enabled: true
                        port: 3000
                        protocol: http
                        targetPort: 3000
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            probes:
                                liveness:
                                    enabled: true
                                    path: /
                                    type: tcp
                                readiness:
                                    enabled: false
                                    type: tcp
                                startup:
                                    enabled: false
                                    type: tcp
                replicas: 1
                type: Deployment
