---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus
    namespace: prometheus
spec:
    interval: 15m
    chart:
        spec:
            chart: prometheus
            version: 19.29.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false
    releaseName: prometheus
    values:
        configmap:
            grafana-datasource:
                data:
                    datasource.yaml: |-
                        apiVersion: 1
                        datasources:
                        - name: Prometheus
                          type: prometheus
                          uid: {{ .Values.grafana.datasource.uid | default "prometheus" }}
                          url: http://{{ include "tc.v1.common.lib.chart.names.fullname" $ }}.{{ include "tc.v1.common.lib.metadata.namespace" (dict "rootCtx" $ "objectData" . "caller" "Configmap") }}:{{ .Values.service.main.ports.main.port }}
                          access: proxy
                          isDefault: {{ .Values.grafana.datasource.default | default true }}
                          jsonData:
                            httpMethod: {{ .Values.grafana.datasource.httpMethod | default "POST" }}
                            timeInterval: {{ .Values.grafana.datasource.scrapeInterval | default "30s" }}
                            {{- if .Values.grafana.datasource.timeout }}
                            timeout: {{ .Values.grafana.datasource.timeout }}
                            {{- end }}
                enabled: '{{ if .Values.grafana.datasource.enabled }}true{{ else }}false{{ end }}'
                labels:
                    grafana_datasources: "1"
        exporters:
            kube-state-metrics:
                enabled: true
            node-exporter:
                enabled: true
        grafana:
            datasource:
                default: true
                enabled: true
                httpMethod: POST
                scrapeInterval: 30s
                uid: prometheus
