---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: flaresolverr
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: flaresolverr
            version: 16.1.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
      createNamespace: true
      remediation:
        retries: 3
    upgrade:
      cleanupOnFail: true
      remediation:
        retries: 3
    uninstall:
      keepHistory: false

    values:
        TZ: America/Montreal
        credentials:
            s3:
                type: s3
                url: "${S3URL}"
                bucket: "${S3BUCKET}"
                accessKey: "${S3ID}"
                secretKey: "${S3KEY}"
                encrKey: "${S3ENCRKEY}"
        persistence:
            config:
                enabled: true
                mountPath: /config
                volsync:
                    - credentials: s3
                      dest:
                        enabled: true
                      name: s3
                      src:
                        enabled: true
                      type: restic
